# define the `Secret` to define the necessary environment variables for the mongo server and mongo-express.
# username : user, password: 1234

apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  mongo-root-username: dXNlcg==
  mongo-root-password: MTIzNA==